export default {
    'Roboto': 'google',
    'Sawarabi Mincho': 'google',
    'Open Sans': 'google',
    'Lato': 'google',
    'Anton': 'google',
    'Bubbler One': 'google',
    'Nunito': 'google',
    'Pathway Gothic One': 'google',
    'Six Caps': 'google',
    'Sorts Mill Goudy': 'google',
    'Vollkorn': 'google',
    'Merriweather': 'google',
    'Rokkitt': 'google',
    'Josefin Slab': 'google',
    'Cabin Sketch': 'google',
    'Amatic SC': 'google',
    'Rock Salt': 'google',
    'Great Vibes': 'google',
    'Miltonian': 'google',
    'Miltonian Tattoo': 'google',
    'Pacifico': 'google',
    'Special Elite': 'google',
    'Sacramento': 'google',
    'Itim': 'google',
    'Monsieur La Doulaise': 'google',
    'Pinyon Script': 'google',
    'Miss Fajardose': 'google',
    'Creepster': 'google',
    'Abril Fatface': 'google',
    'Fredoka One': 'google',
    'Designed by Astigmatic': 'google',
    'Bangers': 'google',
    'Sigmar One': 'google',
    'Monoton': 'google',
    'UnifrakturMaguntia': 'google',
    'Mountains of Christmas': 'google',
    'Bungee Shade': 'google',
    'Faster One': 'google',
    'Sail': 'google',
    'Nosifer': 'google',
    'Londrina Outline': 'google',
    'Libre Barcode 39 Extended Text': 'google',
    'Elsie Swash Caps': 'google',
    'Monofett': 'google',
    'Butcherman': 'google',
    'Hanalei': 'google',
    //
    'hakidame': 'custom',
}
